### ISSUE TITLE
Deprecation warning: moment construction falls back to js Date

### ISSUE THREAD

**Issue by mirague** [urish/angular-moment#191]
Would it be possible to address the use of this deprecated approach?
I'm using version `1.0.0-beta.2`

```
Deprecation warning: moment construction falls back to js Date. This is discouraged 
and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Error
    at Function.createFromInputFallback (http://local.weedfrog.com/bower_components/moment/moment.js:746:36)
    at configFromString (http://local.weedfrog.com/bower_components/moment/moment.js:826:32)
    at configFromInput (http://local.weedfrog.com/bower_components/moment/moment.js:1353:13)
    at prepareConfig (http://local.weedfrog.com/bower_components/moment/moment.js:1340:13)
    at createFromConfig (http://local.weedfrog.com/bower_components/moment/moment.js:1307:44)
    at createLocalOrUTC (http://local.weedfrog.com/bower_components/moment/moment.js:1385:16)
    at local__createLocal (http://local.weedfrog.com/bower_components/moment/moment.js:1389:16)
    at utils_hooks__hooks (http://local.weedfrog.com/bower_components/moment/moment.js:16:29)
    at preprocessDate (http://local.weedfrog.com/bower_components/angular-moment/angular-moment.js:396:13)
    at updateMoment (http://local.weedfrog.com/bower_components/angular-moment/angular-moment.js:251:35)
```

**Comment by urish** [comment]
This happens because you passed a string to `am-time-ago`. Try passing a javascript date object instead, or explicitly specifying the format string for the given date using the `amParse` filter:

```html
<span am-time-ago="message.time | amParse:'YYYY.MM.DD HH:mm:ss'"></span>
```

**Comment by mirague** [comment]
Using `amDateFormat` fixed it, thanks for the reply!

**Comment by urish** [comment]
You're welcome :)
